import Image from 'next/image'
import Head from 'next/head'
import Main from '../components/Main'
import Navbar from '../components/Navbar'
import About from '../components/About'
import Skills from '../components/Skills'
import Projects from '../components/Projects'
import Contact from '../components/Contact'
import {useState} from 'react'



export default function Home() {

// States 

//To keep track of the 
  const [showModal, setShowModal] = useState(false)

//Function for copying to clipboard
//Set state to true when text is copied, then time out at 5 seconds
  const copiedTextModal = () => {
      setShowModal(true)
      setTimeout(() => {
          setShowModal(false)
      }, 5000)
  }

  return (
    <div>
        <Head>
          <title>Nikki Calamia | Software Engineer </title>
         <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" /> 
        </Head>
      <Navbar showModal={showModal} copiedTextModal={copiedTextModal}/>
      <Main showModal={showModal} copiedTextModal={copiedTextModal}/>
      <About/>
      <Skills/>
      <Projects/>
      <Contact />
    </div>
  )
}

